### ISSUE TITLE
Any iteration possibility? or find key of an item?

### ISSUE THREAD

**Issue by hiqsociety** [ashishgandhi/buffer#5]
Any iteration possibility? or find key of an item?

**Comment by ashishgandhi** [comment]
You can iterate using `Remaining`. Since this supports arbitrary and variable length objects to be stored, a find would have to do a linear scan.

Is this what you were asking? Did you have an implication strategy in mind?

**Comment by ashishgandhi** [comment]
Since I have not heard back in a while, I'll close this issue. But feel free to reopen and/or send a PR.
